# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='labbel for URL config.', max_length=63)),
                ('slug', models.SlugField(unique_for_month='pub_date')),
                ('text', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('startup', models.ManyToManyField(to='organizer.Startup')),
                ('tags', models.ManyToManyField(related_name='blog_posts', to='organizer.Tag')),
            ],
            options={
                'ordering': ['-pub_date', 'title'],
                'get_latest_by': ['pub_date'],
                'verbose_name': ['blog post'],
            },
        ),
    ]
