# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslink',
            options={'get_latest_by': '-pub_date', 'ordering': ['-pub_date'], 'verbose_name': 'news article'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='A label for URL config.', max_length=31, unique=True),
        ),
    ]
